<table class="sliders" style="overflow:{$UIOptions.noscroll ? 'hidden' : 'scroll'}">
    <colgroup>
        <col class="param-name" />
        <col class="bound c0" />
        <col style="min-width:200px" />
        <col class="bound c1" />
    </colgroup>
    <tr>
        <th>Name</th>
        <th>Min</th>
        <th />
        <th>Max</th>
    </tr>
    <!-- The list of individual sliders is generated by iterating over the store containing sliders data-->
    {#each Object.entries($Params) as [key, { a, b, c0, c1, z, locked, display }]}
        <tr class:foo={locked} class="erasable {ff}" data-path={key} data-store="2">
            <td class:unlocked={!locked} class="param-name {ff}" data-store="2">{display}</td>
            <td data-store="2" data-path="{key} c0" class:unlocked={!locked} class="bound c0">
                {c0}
            </td>
            <td>
                <div class="track track2" bind:clientWidth={track_w}>
                    <div
                        data-store="2"
                        data-path="{key} b"
                        class:unlocked={!locked}
                        class:foo={locked}
                        class="range"
                        style="width:{(track_w * z) / (c1 - c0)}px; 
              left:{(track_w * (b - z / 2 - c0)) / (c1 - c0)}px;"
                        bind:clientWidth={range_w}
                    />

                    <div
                        class="middle"
                        style="width:{2}px; left:{U.scale(c0, c1, 0, track_w, b)}px;"
                    />
                    <div
                        data-store="2"
                        data-path="{key} a"
                        class:unlocked={!locked}
                        class="thumb"
                        style="left:{U.scale(c0, c1, 0, track_w, a)}px"
                        bind:clientWidth={thumb_w}
                    />
                    <!-- <div
              data-store="2"
              data-path="{key} a"
              class:unlocked={!locked}
              style="left:{U.scale(c0, c1, 0, track_w, a)}px;
              top: -30px;
              position:relative
              "
              bind:clientWidth={thumb_w}
            >{a}</div> -->
                </div>
            </td>
            <td data-store="2" data-path="{key} c1" class:unlocked={!locked} class="bound c1">
                {c1}
            </td>
        </tr>
    {/each}
</table>
