<script>
    import { createEventDispatcher } from 'svelte';
    import { UIOptions } from '../lib/UIState';
</script>

<table class="sliders" style="overflow:{$UIOptions.noscroll ? 'hidden' : 'scroll'}">
    <colgroup>
        <col class="col1" />
        <col class="col2 c0" />
        <col class="col3"/>
        <col class="col4 c1" />
    </colgroup>
    <!-- The list of individual sliders is generated by iterating over the store containing sliders data-->
    <slot></slot>
</table>

<style>
.col1{
    width: 100px;
}
.col2{
    width: 50px
}

.col3{
    min-width: 200px;
}
.col4{
    width: 2em
}
</style>
